# This starts databases for local development or integration tests as if they were launched locally.
# Run `docker-compose up -d`
# Shut down and clean up: `docker-compose down`
version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mariadb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  clickhouse:
    image: yandex/clickhouse-server:20.1
    ports:
      - 8123:8123
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123ABCdef@!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123"
    ports:
      - 27017:27017
